-- ============================================================
-- Inspección tablas adicionales HABEJICO
-- ============================================================

-- 1. TKCLIENTES2 (email y datos adicionales clientes)
PRINT '=== TKCLIENTES2 - Columnas ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TKCLIENTES2'
ORDER BY ORDINAL_POSITION;

PRINT '=== TKCLIENTES2 - Muestra ==='
SELECT TOP 3 * FROM TKCLIENTES2;

-- 2. TCTERCEROS (terceros - info general)
PRINT '=== TCTERCEROS - Columnas ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TCTERCEROS'
ORDER BY ORDINAL_POSITION;

PRINT '=== TCTERCEROS - Muestra ==='
SELECT TOP 3 * FROM TCTERCEROS;

-- 3. TCTERCEROS2 (terceros info adicional)
PRINT '=== TCTERCEROS2 - Columnas ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TCTERCEROS2'
ORDER BY ORDINAL_POSITION;

PRINT '=== TCTERCEROS2 - Muestra ==='
SELECT TOP 3 * FROM TCTERCEROS2;

-- 4. TMUSUARIOSNUI
PRINT '=== TMUSUARIOSNUI - Columnas ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMUSUARIOSNUI'
ORDER BY ORDINAL_POSITION;

PRINT '=== TMUSUARIOSNUI - Muestra ==='
SELECT TOP 3 * FROM TMUSUARIOSNUI;

-- 5. TKCLIENTES (principal)
PRINT '=== TKCLIENTES - Columnas ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TKCLIENTES'
ORDER BY ORDINAL_POSITION;

PRINT '=== TKCLIENTES - Muestra ==='
SELECT TOP 3 * FROM TKCLIENTES;
