-- ============================================================
-- Inspección de tablas clave HABEJICO para agendamiento
-- ============================================================

-- 1. Estructura de TMCITASUSUARIOS (citas/agendamiento)
PRINT '=== TMCITASUSUARIOS ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMCITASUSUARIOS'
ORDER BY ORDINAL_POSITION;

-- 2. Muestra de datos de citas
PRINT '=== MUESTRA CITAS (TOP 3) ==='
SELECT TOP 3 * FROM TMCITASUSUARIOS;

-- 3. Estructura de TMMEDICOS (médicos)
PRINT '=== TMMEDICOS ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMMEDICOS'
ORDER BY ORDINAL_POSITION;

-- 4. Muestra médicos
PRINT '=== MUESTRA MEDICOS (TOP 3) ==='
SELECT TOP 3 * FROM TMMEDICOS;

-- 5. Estructura TMTURNOSMEDICOS (horarios)
PRINT '=== TMTURNOSMEDICOS ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMTURNOSMEDICOS'
ORDER BY ORDINAL_POSITION;

-- 6. Muestra turnos
PRINT '=== MUESTRA TURNOS (TOP 3) ==='
SELECT TOP 3 * FROM TMTURNOSMEDICOS;

-- 7. Estructura TMUSUARIOSASEGURAMIENTO (pacientes)
PRINT '=== TMUSUARIOSASEGURAMIENTO ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMUSUARIOSASEGURAMIENTO'
ORDER BY ORDINAL_POSITION;

-- 8. Muestra pacientes
PRINT '=== MUESTRA PACIENTES (TOP 3) ==='
SELECT TOP 3 * FROM TMUSUARIOSASEGURAMIENTO;

-- 9. Estructura TMESPECIALIDADES
PRINT '=== TMESPECIALIDADES ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMESPECIALIDADES'
ORDER BY ORDINAL_POSITION;

-- 10. Muestra especialidades
PRINT '=== MUESTRA ESPECIALIDADES (TOP 10) ==='
SELECT TOP 10 * FROM TMESPECIALIDADES;

-- 11. Estructura TMCONSULTORIOS
PRINT '=== TMCONSULTORIOS ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMCONSULTORIOS'
ORDER BY ORDINAL_POSITION;

-- 12. Muestra consultorios
PRINT '=== MUESTRA CONSULTORIOS (TOP 5) ==='
SELECT TOP 5 * FROM TMCONSULTORIOS;

-- 13. Estructura TMTURNOCONSULTORIO
PRINT '=== TMTURNOCONSULTORIO ==='
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMTURNOCONSULTORIO'
ORDER BY ORDINAL_POSITION;

-- 14. Muestra turno consultorio
PRINT '=== MUESTRA TURNO CONSULTORIO (TOP 3) ==='
SELECT TOP 3 * FROM TMTURNOCONSULTORIO;
